import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Container } from "react-bootstrap";
import { Fragment } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container className="py-5">{children}</Container>
      </body>
    </html>
  );
}

export default function LayoutWrapper({ children }) {
  return (
    <Fragment>
      <RootLayout children={children} />
    </Fragment>
  );
}
